### ISSUE TITLE
The code has been reproduced again, not as good as you said, or it may have been a fitting problem.

### ISSUE THREAD

**Issue by zzyzzu** [wuzhiye7/Induction-Network-on-FewRel#2]
![文本分类](https://user-images.githubusercontent.com/33992767/62038210-e95a7900-b227-11e9-8535-f26fe25eb74a.png)

**Comment by Dreamliking** [comment]
Hi，Do you have this code to have the result? N = 5, K= 10

**Comment by wuzhiye7** [comment]
yes! remove the l2_losss, you can get a good result
